pipeline {
    agent {
        label 'agent1'
    }
    environment {
        DOCKER_PWD = credentials('docker-pwd')
        DEV = 'https://dev.epam.pp.ua'
        PROD = 'https://epam.pp.ua'
        IP_DEV = '3.122.192.76'
        IP_PROD = '52.29.93.252'
        REGISTRY_NAME = 'soubi8/fp'
        APP = 'api'
    }
    stages {
        stage('SCM Checkout') {
            steps {
                git credentialsId: 'jenkins_key', url: 'git@github.com:Soubi8/realworld-springboot-java.git'
            }
        }
        stage('Build App to Docker Image') {
            steps {
                echo "============== Building App to Docker Image =============="
                sh """
                    git checkout ${BRANCH_NAME}
                    ls -la
                    sudo usermod -aG docker $USER
                    sudo chown $USER /var/run/docker.sock
                    docker build --pull -t ${REGISTRY_NAME}:${BRANCH_NAME} .
                """
            }
        }
        stage('Push Docker Image') {
            steps {  // Add credential helper
                echo "============== Pushing Docker Image to DockerHub =============="
                sh 'echo "$DOCKER_PWD" | docker login -u soubi8 --password-stdin'
                sh "docker push ${REGISTRY_NAME}:${BRANCH_NAME}"
                sh 'docker logout' 
            }
        }
        stage('Deploy to Dev Server') {
            when {
                branch 'develop'
            }
            steps {
                script {
                    def dockerRun = "docker run --rm --name ${APP} -d -p 8080:8080 ${REGISTRY_NAME}:${BRANCH_NAME}"
                    def dockerStop = "docker stop ${APP}"
                    sshagent(['aws_fp_api']) {
                        sh "ssh -o StrictHostKeyChecking=no ubuntu@${IP_DEV} '${dockerRun} || (${dockerStop} && ${dockerRun})'"
                    }
                }
            }
        }
        stage('Deploy to Prod Server') {
            when {
                branch 'master'
            }
            steps {
                script {
                    def dockerRun = "docker run --rm --name ${APP} -d -p 8080:8080 ${REGISTRY_NAME}:${BRANCH_NAME}"
                    def dockerStop = "docker stop ${APP}"
                    sshagent(['aws_fp_api']) {
                        sh "ssh -o StrictHostKeyChecking=no ubuntu@${IP_PROD} '${dockerRun} || (${dockerStop} && ${dockerRun})'"
                    }
                }
            }
        }
        stage('Test the API on Dev Server') {
            when {
                branch 'develop'
            }
            steps {
                sh """
                    bash ./200.sh ${DEV}/articles
                    export APIURL=${DEV} && bash ./doc/run-api-tests.sh
                """
            }
        }
        stage('Test the API on Prod Server') {
            when {
                branch 'master'
            }
            steps {
                sh """
                    bash ./200.sh ${PROD}/articles
                    export APIURL=${PROD} && bash ./doc/run-api-tests.sh
                """
            }
        }
        stage('Merge Request to Master branch') {
            when {
                branch 'develop'
            }
            steps {
                withCredentials([string(credentialsId: 'git_token', variable: 'GIT_TOKEN')]) {
                    script{
                        sh '''
                            curl \\
                                -X POST \\
                                -H \"Accept: application/vnd.github.v3+json\" \\
                                -H \"Authorization: token ${GIT_TOKEN}\" \\
                                https://api.github.com/repos/soubi8/realworld-springboot-java/merges \\
                                -d '{\"base\":\"master\",\"head\":\"develop\",\"commit_message\":\"Added new feature for API\"}'
                        '''
                    }
                }
            }
        }
    }
}
