version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    networks:
      - backend
    user: root
    ports:
      - 443:8080
      - 80:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  agent:
    build: 
      context: .
      dockerfile: Dockerfile.agent
    privileged: true
    restart: always
    user: root
    networks:
      - backend
    container_name: agent
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
      - JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
networks:
  backend:
