version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    networks:
      - backend
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    networks:
      - backend
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
networks:
  backend: