FROM jenkins/ssh-agent:jdk11

USER root

RUN apt update -y && \
    apt install -y --no-install-recommends \
    git docker.io npm curl sudo && \
    npm install newman && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN echo "jenkins ALL= NOPASSWD: ALL" >> /etc/sudoers