- hosts: "*"
  vars:
    workdir: ~/jenkins_compose
  tasks:
    - name: Checking if workdir exists
      stat: path={{workdir}}
      register: status
    - name: Creating workdir
      shell: mkdir {{workdir}}
      when: not status.stat.exists
    - name: Copying docker_compose.yml
      copy:
        src: ./files/docker-compose.yml
        dest: "{{workdir}}/docker-compose.yml"
        owner: max
        group: max
        mode: 0644
    - name: Generating SSH key "{{ssh_key_filename}}"
      vars:
        ssh_key_filename: jenkins_agent
      openssh_keypair:
        path: "{{workdir}}/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no
    - name: Passing key to docker_compose.yml
      shell: echo "JENKINS_AGENT_SSH_PUBKEY=$(cat {{workdir}}/jenkins_agent.pub)" > {{workdir}}/.env
    - name: Starting Docker Compose
      shell: docker compose -f {{workdir}}/docker-compose.yml up -d
    - name: Waiting for Jenkins to start
      become: yes
      wait_for:
        path: /home/max/jenkins_compose/jenkins_configuration/secrets/initialAdminPassword
        state: present
    - name: Showing the initial pw for Jenkins
      become: yes
      shell: cat /home/max/jenkins_compose/jenkins_configuration/secrets/initialAdminPassword
      register: result
    - debug:
        var: result.stdout